# Конфигурация бота Telegram
# Этот файл должен быть сохранен как frontend/conf/config/bot.yaml

token: ""

# Настройки бота
skip_updates: true
polling_timeout: 30
retry_timeout: 5

# Настройки команд бота
commands:
  - command: "start"
    description: "Начать работу с ботом"
  - command: "help"
    description: "Получить справку"
  - command: "language"
    description: "Выбрать язык для изучения"
  - command: "study"
    description: "Начать изучение слов"
  - command: "settings"
    description: "Настройки процесса обучения"
  - command: "stats"
    description: "Показать статистику"
  - command: "hint"
    description: "Информация о подсказках"
  - command: "show_big"
    description: "Показать текущее слово крупно"
  - command: "admin"
    description: "Режим администратора"

# Настройки для администраторов
admin:
  # Список ID администраторов (соответствует BOT_ADMIN_USER_IDS в .env)
  admin_ids: "1234567,7654321"

# Настройки распознавания речи
voice_recognition:
  # Включение/отключение распознавания голосовых сообщений
  enabled: true
  
  # Путь к директории для временных файлов
  temp_dir: "temp"
  
  # Размер модели Whisper ("tiny", "base", "small", "medium", "large")
  model_size: "small"
  
  # Язык распознавания
  language: "ru"
  
  # Максимальная длительность голосового сообщения в секундах
  max_duration: 60

# Настройки генерации изображений слов
word_images:
  # Включение/отключение генерации изображений
  enabled: true
  
  # Путь к директории для временных файлов изображений
  temp_dir: "temp"
  
  # Размеры изображения
  width: 800
  height: 750
  
  # Цвета (RGB значения)
  colors:
    background: [255, 255, 255]  # Белый фон
    text: [50, 50, 50]           # Темно-серый текст
    transcription: [100, 100, 100]  # Серый для транскрипции
    border: [200, 200, 200]      # Светло-серая рамка
  
  # Размеры шрифтов
  fonts:
    word_size: 480           # Размер шрифта для слова
    transcription_size: 160  # Размер шрифта для транскрипции
  
  # Автоочистка временных файлов (в секундах)
  cleanup_delay: 300  # 5 минут
  
  # Сохранять ли временные файлы для отладки
  save_debug_files: false
