# Основная конфигурация приложения
# Этот файл должен быть сохранен как frontend/conf/config/default.yaml

# Подключение других конфигурационных файлов
defaults:
  - _self_
  - bot@bot
  - api@api
  - logging@logging
  - learning@learning
  - voice_recognition@voice_recognition 
  - show_big@show_big
  - writing_images@writing_images 

# Настройки приложения
app:
  # Название приложения
  name: "Language Learning Bot"
  # Окружение (development, production)
  environment: "development"
  
# Настройки загрузки файлов
upload:
  # Директория для загруженных файлов
  folder: "./uploads"
  # Максимальный размер загружаемого файла в байтах
  max_size: 10485760  # 10MB
  
  # Настройки по умолчанию для пользователей
  default_settings:
    # Показывать ли картинки написания по умолчанию
    show_writing_images: true
