# Конфигурация процесса обучения
# Этот файл должен быть сохранен как frontend/conf/config/learning.yaml

# Настройки процесса обучения (значения по умолчанию)
# Стартовая позиция для слов (с какого номера начинать)
start_position: 1
# Флаг пропуска помеченных слов
skip_marked: false
# Флаг использования даты проверки
use_check_date: true
# Максимальный интервал для повторения (в днях)
max_interval: 32
# Начальный интервал между проверками (в днях)
default_interval: 1  # Соответствует DEFAULT_INTERVAL_DAYS в .env
# Коэффициент роста интервала при успешном запоминании
interval_multiplier: 2