
# Настройки генерации изображений слов

# Включение/отключение генерации изображений
enabled: true

# Путь к директории для временных файлов изображений
temp_dir: "temp"

# Размеры изображения
width: 800
height: 750

# Цвета (RGB значения)
colors:
  background: [255, 255, 255]  # Белый фон
  text: [50, 50, 50]           # Темно-серый текст
  transcription: [100, 100, 100]  # Серый для транскрипции
  border: [200, 200, 200]      # Светло-серая рамка

# Размеры шрифтов
fonts:
  word_size: 480           # Размер шрифта для слова
  transcription_size: 160  # Размер шрифта для транскрипции

# Автоочистка временных файлов (в секундах)
cleanup_delay: 300  # 5 минут

# Сохранять ли временные файлы для отладки
save_debug_files: false

