
# Настройки распознавания речи

# Включение/отключение распознавания голосовых сообщений
enabled: true

# Путь к директории для временных файлов
temp_dir: "temp"

# Размер модели Whisper ("tiny", "base", "small", "medium", "large")
model_size: "small"

# Язык распознавания
language: "ru"

# Максимальная длительность голосового сообщения в секундах
max_duration: 60
