# Конфигурация сервиса картинок написания
# Этот файл должен быть сохранен как frontend/conf/config/writing_image_service.yaml

# Настройки для картинок написания
writing_images:
  # Включение/отключение генерации картинок написания
  enabled: true
  
  # URL бэкенд-сервиса для генерации картинок
  service_url: "http://localhost:8600"
  
  # API эндпоинт для генерации
  api_endpoint: "/api/generate-writing-image"
  
  # Настройки запросов к сервису
  timeout: 10  # Таймаут запроса в секундах
  retry_count: 2  # Количество повторных попыток
  retry_delay: 1  # Задержка между попытками
  
  # Параметры генерации
  generation:
    # Размеры изображения для картинок написания
    width: 600
    height: 600
    
    # Качество изображения (1-100)
    quality: 90
    
    # Стиль написания для иероглифов
    style: "traditional"  # traditional, simplified, calligraphy
    
    # Показывать ли направляющие линии
    show_guidelines: true
    
    # Цветовая схема
    colors:
      background: [255, 255, 255]  # Белый фон
      stroke: [0, 0, 0]            # Черные штрихи
      guidelines: [200, 200, 200]   # Серые направляющие
  
  # Кэширование картинок
  cache:
    # Включить кэширование на стороне фронтенда
    enabled: true
    
    # Время жизни кэша в секундах (24 часа)
    ttl: 86400
    
    # Максимальный размер кэша в MB
    max_size_mb: 100
  
  # Заглушка для разработки (пока нет бэкенда)
  development:
    # Использовать заглушку вместо реального сервиса
    use_stub: true
    
    # Задержка заглушки для имитации генерации
    stub_delay: 2.5
    
    # Размер заглушки (пустое изображение)
    stub_size:
      width: 400
      height: 400
      
    # Цвета для заглушки
    stub_colors:
      background: [240, 240, 240]  # Светло-серый фон
      border: [180, 180, 180]      # Серая рамка
      text: [120, 120, 120]        # Серый текст
      
    # Шрифты для заглушки
    stub_fonts:
      size: 24
      family: "Arial, sans-serif"
      