name: amikhalev_word_transcription
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.8
  - pandas=2.0.2
  - requests=2.31.0
  - xlrd=2.0.1
  - openpyxl=3.1.2
  - pip=23.0.1
  - pip:
    - argparse==1.4.0
    - typing==3.7.4.3