
# ==================================================
# ОТДЕЛЬНОЕ ОКРУЖЕНИЕ ДЛЯ WRITING SERVICE
# writing_service/environment.yml
# ==================================================

name: amikhalev_writing_images_service
channels:
  - pytorch
  - conda-forge
  - defaults

dependencies:
  - python=3.10
  - pip>=23.0
  
  # ============ SYSTEM DEPENDENCIES ============
  - conda-forge::git-lfs  # Для загрузки AI моделей
  
  # ============ PYTORCH ============
  - pytorch::pytorch>=2.0.0
  - pytorch::torchvision
  - pytorch::torchaudio
  - pytorch::pytorch-cuda=11.8
  
  # ============ SCIENTIFIC COMPUTING (MINIMAL) ============
  - conda-forge::numpy
  - conda-forge::scipy
  - conda-forge::scikit-learn
  
  # ============ IMAGE PROCESSING ============
  - conda-forge::opencv
  - conda-forge::pillow
  
  # ============ MONITORING ============
  - conda-forge::psutil  # Для GPU мониторинга
  
  # ============ PIP DEPENDENCIES ============
  - pip:
      - -r requirements.txt
