# Основная конфигурация сервиса генерации картинок написания
# Этот файл должен быть сохранен как writing_images_service/conf/config/default.yaml

# Подключение других конфигурационных файлов
defaults:
  - _self_
  - api@api
  - logging@logging
  - generation@generation


# Настройки приложения
app:
  # Название приложения
  name: "Writing Image Service"
  # Версия
  version: "1.0.0"
  # Окружение (development, production)
  environment: "development"
  # Описание
  description: "Service for generating writing images for language learning"
  
# Настройки временных файлов
temp:
  # Директория для временных изображений
  images_dir: "./temp/generated_images"
  # Автоочистка временных файлов (в секундах)
  cleanup_interval: 300  # 5 минут
  # Максимальный возраст файлов для удаления (в секундах)
  max_file_age: 1800  # 30 минут

# Настройки производительности
performance:
  max_concurrent_generations: 5
  generation_timeout: 30
  