# Конфигурация логирования для сервиса генерации картинок написания
# Этот файл должен быть сохранен как writing_service/conf/config/logging.yaml

# Уровень логирования (DEBUG, INFO, WARNING, ERROR, CRITICAL)
level: "INFO"
# Формат сообщений лога
format: "%(asctime)s:{%(levelname)s}[%(filename)s:%(lineno)d]: %(message)s"
# Записывать ли логи в файл
log_to_file: true
# Путь к файлу лога
log_file: "logs/writing_service.log"
# Директория для хранения файлов логов
log_dir: "logs"
# Максимальный размер файла лога перед ротацией (в байтах)
log_file_max_size: 5242880  # 5 MB
# Количество сохраняемых файлов лога при ротации
log_file_backup_count: 3

# Настройки логирования для разработки
development:
  level: "DEBUG"
  log_to_console: true
  
# Настройки логирования для продакшена
production:
  level: "WARNING"
  log_to_console: false
  log_file_max_size: 10485760  # 10 MB
  log_file_backup_count: 5

# Специальные настройки для различных компонентов
loggers:
  # Логирование генерации изображений
  generation:
    level: "INFO"
    include_timing: true
    include_parameters: true
    
  # Логирование HTTP запросов
  requests:
    level: "INFO"
    include_headers: false
    include_body: false
    
  # Логирование ошибок
  errors:
    level: "ERROR"
    include_stack_trace: true
    notify_on_critical: false
    